// Generated by gencpp from file move_robot/OGM.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_OGM_H
#define MOVE_ROBOT_MESSAGE_OGM_H

#include <ros/service_traits.h>


#include <move_robot/OGMRequest.h>
#include <move_robot/OGMResponse.h>


namespace move_robot
{

struct OGM
{

typedef OGMRequest Request;
typedef OGMResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OGM
} // namespace move_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_robot::OGM > {
  static const char* value()
  {
    return "a3ef7e635198434f8c5d1fcc111d7ba4";
  }

  static const char* value(const ::move_robot::OGM&) { return value(); }
};

template<>
struct DataType< ::move_robot::OGM > {
  static const char* value()
  {
    return "move_robot/OGM";
  }

  static const char* value(const ::move_robot::OGM&) { return value(); }
};


// service_traits::MD5Sum< ::move_robot::OGMRequest> should match
// service_traits::MD5Sum< ::move_robot::OGM >
template<>
struct MD5Sum< ::move_robot::OGMRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_robot::OGM >::value();
  }
  static const char* value(const ::move_robot::OGMRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_robot::OGMRequest> should match
// service_traits::DataType< ::move_robot::OGM >
template<>
struct DataType< ::move_robot::OGMRequest>
{
  static const char* value()
  {
    return DataType< ::move_robot::OGM >::value();
  }
  static const char* value(const ::move_robot::OGMRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_robot::OGMResponse> should match
// service_traits::MD5Sum< ::move_robot::OGM >
template<>
struct MD5Sum< ::move_robot::OGMResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_robot::OGM >::value();
  }
  static const char* value(const ::move_robot::OGMResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_robot::OGMResponse> should match
// service_traits::DataType< ::move_robot::OGM >
template<>
struct DataType< ::move_robot::OGMResponse>
{
  static const char* value()
  {
    return DataType< ::move_robot::OGM >::value();
  }
  static const char* value(const ::move_robot::OGMResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_OGM_H
