// Generated by gencpp from file move_robot/sync_startRequest.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_SYNC_STARTREQUEST_H
#define MOVE_ROBOT_MESSAGE_SYNC_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_robot
{
template <class ContainerAllocator>
struct sync_startRequest_
{
  typedef sync_startRequest_<ContainerAllocator> Type;

  sync_startRequest_()
    : check_flag(false)  {
    }
  sync_startRequest_(const ContainerAllocator& _alloc)
    : check_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _check_flag_type;
  _check_flag_type check_flag;





  typedef boost::shared_ptr< ::move_robot::sync_startRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_robot::sync_startRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sync_startRequest_

typedef ::move_robot::sync_startRequest_<std::allocator<void> > sync_startRequest;

typedef boost::shared_ptr< ::move_robot::sync_startRequest > sync_startRequestPtr;
typedef boost::shared_ptr< ::move_robot::sync_startRequest const> sync_startRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_robot::sync_startRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_robot::sync_startRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_robot::sync_startRequest_<ContainerAllocator1> & lhs, const ::move_robot::sync_startRequest_<ContainerAllocator2> & rhs)
{
  return lhs.check_flag == rhs.check_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_robot::sync_startRequest_<ContainerAllocator1> & lhs, const ::move_robot::sync_startRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_robot::sync_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_robot::sync_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::sync_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::sync_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::sync_startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::sync_startRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_robot::sync_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90af77130be3c7ed1e0b41f6980836dd";
  }

  static const char* value(const ::move_robot::sync_startRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90af77130be3c7edULL;
  static const uint64_t static_value2 = 0x1e0b41f6980836ddULL;
};

template<class ContainerAllocator>
struct DataType< ::move_robot::sync_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_robot/sync_startRequest";
  }

  static const char* value(const ::move_robot::sync_startRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_robot::sync_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool check_flag\n"
;
  }

  static const char* value(const ::move_robot::sync_startRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_robot::sync_startRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.check_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sync_startRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_robot::sync_startRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_robot::sync_startRequest_<ContainerAllocator>& v)
  {
    s << indent << "check_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.check_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_SYNC_STARTREQUEST_H
