// Generated by gencpp from file move_robot/SyncMotionRequest.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_SYNCMOTIONREQUEST_H
#define MOVE_ROBOT_MESSAGE_SYNCMOTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_robot
{
template <class ContainerAllocator>
struct SyncMotionRequest_
{
  typedef SyncMotionRequest_<ContainerAllocator> Type;

  SyncMotionRequest_()
    : trigger(false)  {
    }
  SyncMotionRequest_(const ContainerAllocator& _alloc)
    : trigger(false)  {
  (void)_alloc;
    }



   typedef uint8_t _trigger_type;
  _trigger_type trigger;





  typedef boost::shared_ptr< ::move_robot::SyncMotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_robot::SyncMotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SyncMotionRequest_

typedef ::move_robot::SyncMotionRequest_<std::allocator<void> > SyncMotionRequest;

typedef boost::shared_ptr< ::move_robot::SyncMotionRequest > SyncMotionRequestPtr;
typedef boost::shared_ptr< ::move_robot::SyncMotionRequest const> SyncMotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_robot::SyncMotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_robot::SyncMotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_robot::SyncMotionRequest_<ContainerAllocator1> & lhs, const ::move_robot::SyncMotionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.trigger == rhs.trigger;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_robot::SyncMotionRequest_<ContainerAllocator1> & lhs, const ::move_robot::SyncMotionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_robot::SyncMotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::SyncMotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::SyncMotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6d1152a533bdef9ec687318c8e489b0";
  }

  static const char* value(const ::move_robot::SyncMotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6d1152a533bdef9ULL;
  static const uint64_t static_value2 = 0xec687318c8e489b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_robot/SyncMotionRequest";
  }

  static const char* value(const ::move_robot::SyncMotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool trigger\n"
;
  }

  static const char* value(const ::move_robot::SyncMotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncMotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_robot::SyncMotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_robot::SyncMotionRequest_<ContainerAllocator>& v)
  {
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_SYNCMOTIONREQUEST_H
