// Generated by gencpp from file move_robot/SyncMotion.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_SYNCMOTION_H
#define MOVE_ROBOT_MESSAGE_SYNCMOTION_H

#include <ros/service_traits.h>


#include <move_robot/SyncMotionRequest.h>
#include <move_robot/SyncMotionResponse.h>


namespace move_robot
{

struct SyncMotion
{

typedef SyncMotionRequest Request;
typedef SyncMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncMotion
} // namespace move_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_robot::SyncMotion > {
  static const char* value()
  {
    return "e22398fd32450a580e4c379bfee2569b";
  }

  static const char* value(const ::move_robot::SyncMotion&) { return value(); }
};

template<>
struct DataType< ::move_robot::SyncMotion > {
  static const char* value()
  {
    return "move_robot/SyncMotion";
  }

  static const char* value(const ::move_robot::SyncMotion&) { return value(); }
};


// service_traits::MD5Sum< ::move_robot::SyncMotionRequest> should match
// service_traits::MD5Sum< ::move_robot::SyncMotion >
template<>
struct MD5Sum< ::move_robot::SyncMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_robot::SyncMotion >::value();
  }
  static const char* value(const ::move_robot::SyncMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_robot::SyncMotionRequest> should match
// service_traits::DataType< ::move_robot::SyncMotion >
template<>
struct DataType< ::move_robot::SyncMotionRequest>
{
  static const char* value()
  {
    return DataType< ::move_robot::SyncMotion >::value();
  }
  static const char* value(const ::move_robot::SyncMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_robot::SyncMotionResponse> should match
// service_traits::MD5Sum< ::move_robot::SyncMotion >
template<>
struct MD5Sum< ::move_robot::SyncMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_robot::SyncMotion >::value();
  }
  static const char* value(const ::move_robot::SyncMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_robot::SyncMotionResponse> should match
// service_traits::DataType< ::move_robot::SyncMotion >
template<>
struct DataType< ::move_robot::SyncMotionResponse>
{
  static const char* value()
  {
    return DataType< ::move_robot::SyncMotion >::value();
  }
  static const char* value(const ::move_robot::SyncMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_SYNCMOTION_H
