// Generated by gencpp from file move_robot/xycoord.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_XYCOORD_H
#define MOVE_ROBOT_MESSAGE_XYCOORD_H

#include <ros/service_traits.h>


#include <move_robot/xycoordRequest.h>
#include <move_robot/xycoordResponse.h>


namespace move_robot
{

struct xycoord
{

typedef xycoordRequest Request;
typedef xycoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct xycoord
} // namespace move_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_robot::xycoord > {
  static const char* value()
  {
    return "468f9ac078489289ae3d0296932d3837";
  }

  static const char* value(const ::move_robot::xycoord&) { return value(); }
};

template<>
struct DataType< ::move_robot::xycoord > {
  static const char* value()
  {
    return "move_robot/xycoord";
  }

  static const char* value(const ::move_robot::xycoord&) { return value(); }
};


// service_traits::MD5Sum< ::move_robot::xycoordRequest> should match
// service_traits::MD5Sum< ::move_robot::xycoord >
template<>
struct MD5Sum< ::move_robot::xycoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_robot::xycoord >::value();
  }
  static const char* value(const ::move_robot::xycoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_robot::xycoordRequest> should match
// service_traits::DataType< ::move_robot::xycoord >
template<>
struct DataType< ::move_robot::xycoordRequest>
{
  static const char* value()
  {
    return DataType< ::move_robot::xycoord >::value();
  }
  static const char* value(const ::move_robot::xycoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_robot::xycoordResponse> should match
// service_traits::MD5Sum< ::move_robot::xycoord >
template<>
struct MD5Sum< ::move_robot::xycoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_robot::xycoord >::value();
  }
  static const char* value(const ::move_robot::xycoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_robot::xycoordResponse> should match
// service_traits::DataType< ::move_robot::xycoord >
template<>
struct DataType< ::move_robot::xycoordResponse>
{
  static const char* value()
  {
    return DataType< ::move_robot::xycoord >::value();
  }
  static const char* value(const ::move_robot::xycoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_XYCOORD_H
