(cl:in-package move_robot-msg)
(cl:export '(CURR_VELOCITY_X-VAL
          CURR_VELOCITY_X
          CURR_VELOCITY_Y-VAL
          CURR_VELOCITY_Y
          DES_VELOCITY_X-VAL
          DES_VELOCITY_X
          DES_VELOCITY_Y-VAL
          DES_VELOCITY_Y
          T_ITER-VAL
          T_ITER
          DELTA-VAL
          DELTA
          T_HORIZON-VAL
          T_HORIZON
          AVOID_I-VAL
          AVOID_I
          A_LONG-VAL
          A_LONG
          A_LAT-VAL
          A_LAT
          VEL_MAG-VAL
          VEL_MAG
          A_LONG_LV-VAL
          A_LONG_LV
          A_LAT_WV-VAL
          A_LAT_WV
          ACCEL-VAL
          ACCEL
))